const form = document.getElementById('contact-form');

form.addEventListener('submit', async function (e) {
  e.preventDefault();

  const formData = new FormData(form);
  const action = form.getAttribute('action');

  try {
    const response = await fetch(action, {
      method: 'POST',
      body: formData,
      headers: { 'Accept': 'application/json' }
    });

    if (response.ok) {
      alert('Message sent successfully!');
      form.reset();
    } else {
      alert('Something went wrong. Please try again.');
    }
  } catch (error) {
    alert('Error submitting the form. Please check your internet connection.');
  }
});

// This part of this project was developed using suggestions generated by ChatGPT (OpenAI)
// 17/16/2025: https://chatgpt.com/share/68516205-f950-800b-9444-d3468b7c5790
// Modifications made by Bichiran Gondal