//////SLIDESHOW///////

const slides = document.querySelectorAll('.slideshow img');
const prevBtn = document.getElementById('prevBtn');
const nextBtn = document.getElementById('nextBtn');

let currentIndex = 0;

function showSlide(index) {
  slides.forEach((slide, i) => {
    slide.classList.toggle('active', i === index);
  });
}

prevBtn.addEventListener('click', () => {
  currentIndex = (currentIndex - 1 + slides.length) % slides.length;
  showSlide(currentIndex);
});

nextBtn.addEventListener('click', () => {
  currentIndex = (currentIndex + 1) % slides.length;
  showSlide(currentIndex);
});

// This part of this project was developed using suggestions generated by ChatGPT (OpenAI)
// 17/16/2025: https://chatgpt.com/share/68516df9-9848-800b-a62c-f4b94ce771bd
// Modifications made by Bichiran Gondal